# -*- coding: iso-8859-1 -*-
"""
        MoinMoin - LSL (Linden Scripting Language) Parser version 0.2

    new in this version: compatible with LSL version 1.10.0

    @copyright: 2006 by Thilo Pfennig <tpfennig@gmail.com>
    based on Java parser by Taesu Pyo <bigflood@hitel.net>
    @license: GNU GPL, see COPYING for details.

"""

from MoinMoin.util.ParserBase import ParserBase

Dependencies = []

class Parser(ParserBase):

    parsername = "ColorizedLsl"
    extensions = ['.lsl']
    Dependencies = []

    def setupRules(self):
        ParserBase.setupRules(self)

        self.addRulePair("Comment","/[*]","[*]/")
        self.addRule("Comment","//.*$")
        self.addRulePair("String",'"',r'$|[^\](\\)*"')
        self.addRule("Char",r"'\.'|'[^\]'")
        self.addRule("Number",r"[0-9](\.[0-9]*)?(eE[+-][0-9])?[flFLdD]?|0[xX][0-9a-fA-F]+[ll]?")
        self.addRule("ID","[a-zA-Z_][0-9a-zA-Z_]*")
        self.addRule("SPChar",r"[~!%^&*()+=|\[\]:;,.<>/?{}-]")

        reserved_words = ['default','do','double','else','enum','extends','if','final','finally',
        'float','for','integer','implements','import','int','jump','key','list',
        'long','new','native','package','private','protected','return','rotation','state','static','string',
        'synchronized','vector','while']

        self.addReserved(reserved_words)

        constant_words = ['true','false','null']

        self.addConstant(constant_words)

""" functions (todo)
,llAbs
,llAcos
,llAddToLandBanList
,llAddToLandPassList
,llAdjustSoundVolume
,llAllowInventoryDrop
,llAngleBetween
,llApplyImpulse
,llApplyRotationalImpulse
,llAsin
,llAtan2
,llAttachToAvatar
,llAvatarOnSitTarget
,llAxes2Rot
,llAxisAngle2Rot
,llBase64ToInteger
,llBase64ToString
,llBreakAllLinks
,llBreakLink
,llCeil
,llClearCameraParams
,llCloseRemoteDataChannel
,llCloud
,llCollisionFilter
,llCollisionSound
,llCollisionSprite
,llCos
,llCreateLink
,llCSV2List
,llDeleteSubList
,llDeleteSubString
,llDetachFromAvatar
,llDetectedGrab
,llDetectedGroup
,llDetectedKey
,llDetectedLinkNumber
,llDetectedName
,llDetectedOwner
,llDetectedPos
,llDetectedRot
,llDetectedType
,llDetectedVel
,llDialog
,llDie
,llDumpList2String
,llEdgeOfWorld
,llEjectFromLand
,llEmail
,llEscapeURL
,llEuler2Rot
,llFabs
,llFloor
,llForceMouselook
,llFrand
,llGetAccel
,llGetAgentInfo
,llGetAgentSize
,llGetAlpha
,llGetAndResetTime
,llGetAnimation
,llGetAnimationList
,llGetAttached
,llGetBoundingBox
,llGetCameraPos
,llGetCameraRot
,llGetCenterOfMass
,llGetColor
,llGetCreator
,llGetDate
,llGetEnergy
,llGetForce
,llGetFreeMemory
,llGetGeometricCenter
,llGetGMTclock
,llGetInventoryCreator
,llGetInventoryKey
,llGetInventoryName
,llGetInventoryNumber
,llGetInventoryPermMask
,llGetInventoryType
,llGetKey
,llGetLandOwnerAt
,llGetLinkKey
,llGetLinkName
,llGetLinkNumber
,llGetListEntryType
,llGetListLength
,llGetLocalPos
,llGetLocalRot
,llGetMass
,llGetNextEmail
,llGetNotecardLine
,llGetNumberOfNotecardLines
,llGetNumberOfPrims
,llGetNumberOfSides
,llGetObjectDesc
,llGetObjectMass
,llGetObjectName
,llGetObjectPermMask
,llGetOmega
,llGetOwner
,llGetOwnerKey
,llGetParcelFlags
,llGetPermissions
,llGetPermissionsKey
,llGetPos
,llGetPrimitiveParams
,llGetRegionCorner
,llGetRegionFlags
,llGetRegionFPS
,llGetRegionName
,llGetRegionTimeDilation
,llGetRootPosition
,llGetRootRotation
,llGetRot
,llGetScale
,llGetScriptName
,llGetScriptState
,llGetSimulatorHostname
,llGetStartParameter
,llGetStatus
,llGetSubString
,llGetSunDirection
,llGetTexture
,llGetTextureOffset
,llGetTextureRot
,llGetTextureScale
,llGetTime
,llGetTimeOfDay
,llGetTimestamp
,llGetTorque
,llGetUnixTime
,llGetVel
,llGetWallclock
,llGiveInventory
,llGiveInventoryList
,llGiveMoney
,llGround
,llGroundContour
,llGroundNormal
,llGroundRepel
,llGroundSlope
,llHTTPRequest
,llInsertString
,llInstantMessage
,llIntegerToBase64
,llKey2Name
,llList2CSV
,llList2Float
,llList2Integer
,llList2Key
,llList2List
,llList2ListStrided
,llList2Rot
,llList2String
,llList2Vector
,llListen
,llListenControl
,llListenRemove
,llListFindList
,llListInsertList
,llListRandomize
,llListReplaceList
,llListSort
,llListStatistics
,llLoadURL
,llLog
,llLog10
,llLookAt
,llLoopSound
,llLoopSoundMaster
,llLoopSoundSlave
,llMapDestination
,llMD5String
,llMessageLinked
,llMinEventDelay
,llModifyLand
,llModPow
,llMoveToTarget
,llOffsetTexture
,llOpenRemoteDataChannel
,llOverMyLand
,llOwnerSay
,llParcelMediaCommandList
,llParcelMediaQuery
,llParseString2List
,llParseStringKeepNulls
,llParticleSystem
,llPassCollisions
,llPassTouches
,llPlaySound
,llPlaySoundSlave
,llPointAt
,llPow
,llPreloadSound
,llPushObject
,llReleaseCamera
,llReleaseControls
,llRemoteDataReply
,llRemoteDataSetRegion
,llRemoteLoadScriptPin
,llRemoveFromLandBanList
,llRemoveFromLandPassList
,llRemoveInventory
,llRemoveVehicleFlags
,llRequestAgentData
,llRequestInventoryData
,llRequestPermissions
,llRequestSimulatorData
,llResetOtherScript
,llResetScript
,llResetTime
,llRezAtRoot
,llRezObject
,llRot2Angle
,llRot2Axis
,llRot2Euler
,llRot2Fwd
,llRot2Left
,llRot2Up
,llRotateTexture
,llRotBetween
,llRotLookAt
,llRotTarget
,llRotTargetRemove
,llRound
,llSameGroup
,llSay
,llScaleTexture
,llScriptDanger
,llSendRemoteData
,llSensor
,llSensorRemove
,llSensorRepeat
,llSetAlpha
,llSetBuoyancy
,llSetCameraAtOffset
,llSetCameraEyeOffset
,llSetCameraParams
,llSetColor
,llSetDamage
,llSetForce
,llSetForceAndTorque
,llSetHoverHeight
,llSetLinkAlpha
,llSetLinkColor
,llSetLocalRot
,llSetObjectDesc
,llSetObjectName
,llSetParcelMusicURL
,llSetPayPrice
,llSetPos
,llSetPrimitiveParams
,llSetRemoteScriptAccessPin
,llSetRot
,llSetScale
,llSetScriptState
,llSetSitText
,llSetSoundQueueing
,llSetStatus
,llSetText
,llSetTexture
,llSetTextureAnim
,llSetTimerEvent
,llSetTorque
,llSetTouchText
,llSetVehicleFlags
,llSetVehicleFloatParam
,llSetVehicleRotationParam
,llSetVehicleType
,llSetVehicleVectorParam
,llShout
,llSin
,llSitTarget
,llSleep
,llSqrt
,llStartAnimation
,llStopAnimation
,llStopHover
,llStopLookAt
,llStopMoveToTarget
,llStopPointAt
,llStopSound
,llStringLength
,llStringToBase64
,llSubStringIndex
,llTakeControls
,llTan
,llTarget
,llTargetOmega
,llTargetRemove
,llTeleportAgentHome
,llToLower
,llToUpper
,llTriggerSound
,llTriggerSoundLimited
,llUnescapeURL
,llUnSit
,llVecDist
,llVecMag
,llVecNorm
,llVolumeDetect
,llWater
,llWhisper
,llWind
,llXorBase64StringsCorrect
"""
