!TCL=1, 
!TITLE=Linden Scripting Language
!SORT=Y
!CHARSET=ANSI

!TEXT=state
state
!
!TEXT=do
do
!
!TEXT=else
else
!
!TEXT=for
for
!
!TEXT=if
if
!
!TEXT=jump
jump
!
!TEXT=return
return
!
!TEXT=string
string
!
!TEXT=while
while
!
!TEXT=float
float
!
!TEXT=integer
integer
!
!TEXT=key
key
!
!TEXT=list
list
!
!TEXT=quaternion
quaternion
!
!TEXT=rotation
rotation
!
!TEXT=string
string
!
!TEXT=vector
vector
!
!TEXT=at_rot_target 
at_rot_target 
!
!TEXT=at_target 
at_target 
!
!TEXT=attach 
attach 
!
!TEXT=changed 
changed 
!
!TEXT=collision 
collision 
!
!TEXT=collision_end 
collision_end 
!
!TEXT=collision_start 
collision_start 
!
!TEXT=control 
control 
!
!TEXT=dataserver 
dataserver 
!
!TEXT=email 
email 
!
!TEXT=land_collision 
land_collision 
!
!TEXT=land_collision_end 
land_collision_end 
!
!TEXT=land_collision_start 
land_collision_start 
!
!TEXT=link_message 
link_message 
!
!TEXT=listen 
listen 
!
!TEXT=money 
money 
!
!TEXT=moving_end 
moving_end 
!
!TEXT=moving_start 
moving_start 
!
!TEXT=no_sensor 
no_sensor 
!
!TEXT=not_at_rot_target 
not_at_rot_target 
!
!TEXT=not_at_target 
not_at_target 
!
!TEXT=object_rez 
object_rez 
!
!TEXT=on_rez 
on_rez 
!
!TEXT=print
print
!
!TEXT=remote_data 
remote_data 
!
!TEXT=run_time_permissions 
run_time_permissions 
!
!TEXT=sensor 
sensor 
!
!TEXT=state_entry 
state_entry 
!
!TEXT=state_exit 
state_exit 
!
!TEXT=timer 
timer 
!
!TEXT=touch 
touch 
!
!TEXT=touch_end 
touch_end 
!
!TEXT=touch_start 
touch_start 
!
!TEXT=ACTIVE
ACTIVE
!
!TEXT=AGENT
AGENT
!
!TEXT=AGENT_ALWAYS_RUN
AGENT_ALWAYS_RUN
!
!TEXT=AGENT_ATTACHMENTS
AGENT_ATTACHMENTS
!
!TEXT=AGENT_AWAY
AGENT_AWAY
!
!TEXT=AGENT_BUSY
AGENT_BUSY
!
!TEXT=AGENT_CROUCHING
AGENT_CROUCHING
!
!TEXT=AGENT_FLYING
AGENT_FLYING
!
!TEXT=AGENT_IN_AIR
AGENT_IN_AIR
!
!TEXT=AGENT_MOUSELOOK
AGENT_MOUSELOOK
!
!TEXT=AGENT_ON_OBJECT
AGENT_ON_OBJECT
!
!TEXT=AGENT_SCRIPTED
AGENT_SCRIPTED
!
!TEXT=AGENT_SITTING
AGENT_SITTING
!
!TEXT=AGENT_TYPING
AGENT_TYPING
!
!TEXT=AGENT_WALKING
AGENT_WALKING
!
!TEXT=ALL_SIDES
ALL_SIDES
!
!TEXT=ANIM_ON
ANIM_ON
!
!TEXT=ATTACH_BACK
ATTACH_BACK
!
!TEXT=ATTACH_BELLY
ATTACH_BELLY
!
!TEXT=ATTACH_CHEST
ATTACH_CHEST
!
!TEXT=ATTACH_CHIN
ATTACH_CHIN
!
!TEXT=ATTACH_HEAD
ATTACH_HEAD
!
!TEXT=ATTACH_LEAR
ATTACH_LEAR
!
!TEXT=ATTACH_LEYE
ATTACH_LEYE
!
!TEXT=ATTACH_LFOOT
ATTACH_LFOOT
!
!TEXT=ATTACH_LHAND
ATTACH_LHAND
!
!TEXT=ATTACH_LHIP
ATTACH_LHIP
!
!TEXT=ATTACH_LLARM
ATTACH_LLARM
!
!TEXT=ATTACH_LLLEG
ATTACH_LLLEG
!
!TEXT=ATTACH_LPEC
ATTACH_LPEC
!
!TEXT=ATTACH_LSHOULDER
ATTACH_LSHOULDER
!
!TEXT=ATTACH_LUARM
ATTACH_LUARM
!
!TEXT=ATTACH_LULEG
ATTACH_LULEG
!
!TEXT=ATTACH_MOUTH
ATTACH_MOUTH
!
!TEXT=ATTACH_NOSE
ATTACH_NOSE
!
!TEXT=ATTACH_PELVIS
ATTACH_PELVIS
!
!TEXT=ATTACH_REAR
ATTACH_REAR
!
!TEXT=ATTACH_REYE
ATTACH_REYE
!
!TEXT=ATTACH_RFOOT
ATTACH_RFOOT
!
!TEXT=ATTACH_RHAND
ATTACH_RHAND
!
!TEXT=ATTACH_RHIP
ATTACH_RHIP
!
!TEXT=ATTACH_RLARM
ATTACH_RLARM
!
!TEXT=ATTACH_RLLEG
ATTACH_RLLEG
!
!TEXT=ATTACH_RPEC
ATTACH_RPEC
!
!TEXT=ATTACH_RSHOULDER
ATTACH_RSHOULDER
!
!TEXT=ATTACH_RUARM
ATTACH_RUARM
!
!TEXT=ATTACH_RULEG
ATTACH_RULEG
!
!TEXT=CHANGED_ALLOWED_DROP
CHANGED_ALLOWED_DROP
!
!TEXT=CHANGED_COLOR
CHANGED_COLOR
!
!TEXT=CHANGED_INVENTORY
CHANGED_INVENTORY
!
!TEXT=CHANGED_LINK
CHANGED_LINK
!
!TEXT=CHANGED_OWNER
CHANGED_OWNER
!
!TEXT=CHANGED_SCALE
CHANGED_SCALE
!
!TEXT=CHANGED_SHAPE
CHANGED_SHAPE
!
!TEXT=CHANGED_TEXTURE
CHANGED_TEXTURE
!
!TEXT=CONTROL_BACK
CONTROL_BACK
!
!TEXT=CONTROL_DOWN
CONTROL_DOWN
!
!TEXT=CONTROL_FWD
CONTROL_FWD
!
!TEXT=CONTROL_LBUTTON
CONTROL_LBUTTON
!
!TEXT=CONTROL_LEFT
CONTROL_LEFT
!
!TEXT=CONTROL_ML_LBUTTON
CONTROL_ML_LBUTTON
!
!TEXT=CONTROL_RIGHT
CONTROL_RIGHT
!
!TEXT=CONTROL_ROT_LEFT
CONTROL_ROT_LEFT
!
!TEXT=CONTROL_ROT_RIGHT
CONTROL_ROT_RIGHT
!
!TEXT=CONTROL_UP
CONTROL_UP
!
!TEXT=DATA_BORN
DATA_BORN
!
!TEXT=DATA_NAME
DATA_NAME
!
!TEXT=DATA_ONLINE
DATA_ONLINE
!
!TEXT=DATA_RATING
DATA_RATING
!
!TEXT=DATA_SIM_POS
DATA_SIM_POS
!
!TEXT=DATA_SIM_STATUS
DATA_SIM_STATUS
!
!TEXT=FALSE
FALSE
!
!TEXT=INVENTORY_ALL
INVENTORY_ALL
!
!TEXT=INVENTORY_ANIMATION
INVENTORY_ANIMATION
!
!TEXT=INVENTORY_BODYPART
INVENTORY_BODYPART
!
!TEXT=INVENTORY_CLOTHING
INVENTORY_CLOTHING
!
!TEXT=INVENTORY_GESTURE
INVENTORY_GESTURE
!
!TEXT=INVENTORY_LANDMARK
INVENTORY_LANDMARK
!
!TEXT=INVENTORY_NOTECARD
INVENTORY_NOTECARD
!
!TEXT=INVENTORY_OBJECT
INVENTORY_OBJECT
!
!TEXT=INVENTORY_SCRIPT
INVENTORY_SCRIPT
!
!TEXT=INVENTORY_SOUND
INVENTORY_SOUND
!
!TEXT=INVENTORY_TEXTURE
INVENTORY_TEXTURE
!
!TEXT=LAND_LARGE_BRUSH
LAND_LARGE_BRUSH
!
!TEXT=LAND_LEVEL
LAND_LEVEL
!
!TEXT=LAND_LOWER
LAND_LOWER
!
!TEXT=LAND_MEDIUM_BRUSH
LAND_MEDIUM_BRUSH
!
!TEXT=LAND_NOISE
LAND_NOISE
!
!TEXT=LAND_RAISE
LAND_RAISE
!
!TEXT=LAND_REVERT
LAND_REVERT
!
!TEXT=LAND_SMALL_BRUSH
LAND_SMALL_BRUSH
!
!TEXT=LAND_SMOOTH
LAND_SMOOTH
!
!TEXT=LINK_ALL_CHILDREN
LINK_ALL_CHILDREN
!
!TEXT=LINK_ALL_OTHERS
LINK_ALL_OTHERS
!
!TEXT=LINK_ROOT
LINK_ROOT
!
!TEXT=LINK_SET
LINK_SET
!
!TEXT=LINK_THIS
LINK_THIS
!
!TEXT=LOOP
LOOP
!
!TEXT=MASK_BASE
MASK_BASE
!
!TEXT=MASK_EVERYONE
MASK_EVERYONE
!
!TEXT=MASK_GROUP
MASK_GROUP
!
!TEXT=MASK_NEXT
MASK_NEXT
!
!TEXT=MASK_OWNER
MASK_OWNER
!
!TEXT=PARCEL_MEDIA_COMMAND_AGENT
PARCEL_MEDIA_COMMAND_AGENT
!
!TEXT=PARCEL_MEDIA_COMMAND_AUTO_ALIGN
PARCEL_MEDIA_COMMAND_AUTO_ALIGN
!
!TEXT=PARCEL_MEDIA_COMMAND_LOOP
PARCEL_MEDIA_COMMAND_LOOP
!
!TEXT=PARCEL_MEDIA_COMMAND_PAUSE
PARCEL_MEDIA_COMMAND_PAUSE
!
!TEXT=PARCEL_MEDIA_COMMAND_PLAY
PARCEL_MEDIA_COMMAND_PLAY
!
!TEXT=PARCEL_MEDIA_COMMAND_STOP
PARCEL_MEDIA_COMMAND_STOP
!
!TEXT=PARCEL_MEDIA_COMMAND_TEXTURE
PARCEL_MEDIA_COMMAND_TEXTURE
!
!TEXT=PARCEL_MEDIA_COMMAND_TIME
PARCEL_MEDIA_COMMAND_TIME
!
!TEXT=PARCEL_MEDIA_COMMAND_UNLOAD
PARCEL_MEDIA_COMMAND_UNLOAD
!
!TEXT=PARCEL_MEDIA_COMMAND_URL
PARCEL_MEDIA_COMMAND_URL
!
!TEXT=PASSIVE
PASSIVE
!
!TEXT=PERMISSION_ATTACH
PERMISSION_ATTACH
!
!TEXT=PERMISSION_CHANGE_JOINTS
PERMISSION_CHANGE_JOINTS
!
!TEXT=PERMISSION_CHANGE_LINKS
PERMISSION_CHANGE_LINKS
!
!TEXT=PERMISSION_CHANGE_PERMISSIONS
PERMISSION_CHANGE_PERMISSIONS
!
!TEXT=PERMISSION_DEBIT
PERMISSION_DEBIT
!
!TEXT=PERMISSION_RELEASE_OWNERSHIP
PERMISSION_RELEASE_OWNERSHIP
!
!TEXT=PERMISSION_REMAP_CONTROLS
PERMISSION_REMAP_CONTROLS
!
!TEXT=PERMISSION_TAKE_CONTROLS
PERMISSION_TAKE_CONTROLS
!
!TEXT=PERMISSION_TRIGGER_ANIMATION
PERMISSION_TRIGGER_ANIMATION
!
!TEXT=PERM_ALL
PERM_ALL
!
!TEXT=PERM_COPY
PERM_COPY
!
!TEXT=PERM_MODIFY
PERM_MODIFY
!
!TEXT=PERM_MOVE
PERM_MOVE
!
!TEXT=PERM_TRANSFER
PERM_TRANSFER
!
!TEXT=PING_PONG
PING_PONG
!
!TEXT=PRIM_BUMP_BARK
PRIM_BUMP_BARK
!
!TEXT=PRIM_BUMP_BLOBS
PRIM_BUMP_BLOBS
!
!TEXT=PRIM_BUMP_BRICKS
PRIM_BUMP_BRICKS
!
!TEXT=PRIM_BUMP_BRIGHT
PRIM_BUMP_BRIGHT
!
!TEXT=PRIM_BUMP_CHECKER
PRIM_BUMP_CHECKER
!
!TEXT=PRIM_BUMP_CONCRETE
PRIM_BUMP_CONCRETE
!
!TEXT=PRIM_BUMP_DARK
PRIM_BUMP_DARK
!
!TEXT=PRIM_BUMP_DISKS
PRIM_BUMP_DISKS
!
!TEXT=PRIM_BUMP_GRAVEL
PRIM_BUMP_GRAVEL
!
!TEXT=PRIM_BUMP_LARGETILE
PRIM_BUMP_LARGETILE
!
!TEXT=PRIM_BUMP_NONE
PRIM_BUMP_NONE
!
!TEXT=PRIM_BUMP_SHINY
PRIM_BUMP_SHINY
!
!TEXT=PRIM_BUMP_SIDING
PRIM_BUMP_SIDING
!
!TEXT=PRIM_BUMP_STONE
PRIM_BUMP_STONE
!
!TEXT=PRIM_BUMP_STUCCO
PRIM_BUMP_STUCCO
!
!TEXT=PRIM_BUMP_SUCTION
PRIM_BUMP_SUCTION
!
!TEXT=PRIM_BUMP_TILE
PRIM_BUMP_TILE
!
!TEXT=PRIM_BUMP_WEAVE
PRIM_BUMP_WEAVE
!
!TEXT=PRIM_BUMP_WOOD
PRIM_BUMP_WOOD
!
!TEXT=PRIM_COLOR
PRIM_COLOR
!
!TEXT=PRIM_HOLE_CIRCLE
PRIM_HOLE_CIRCLE
!
!TEXT=PRIM_HOLE_DEFAULT
PRIM_HOLE_DEFAULT
!
!TEXT=PRIM_HOLE_SQUARE
PRIM_HOLE_SQUARE
!
!TEXT=PRIM_HOLE_TRIANGLE
PRIM_HOLE_TRIANGLE
!
!TEXT=PRIM_MATERIAL
PRIM_MATERIAL
!
!TEXT=PRIM_MATERIAL_FLESH
PRIM_MATERIAL_FLESH
!
!TEXT=PRIM_MATERIAL_GLASS
PRIM_MATERIAL_GLASS
!
!TEXT=PRIM_MATERIAL_LIGHT
PRIM_MATERIAL_LIGHT
!
!TEXT=PRIM_MATERIAL_METAL
PRIM_MATERIAL_METAL
!
!TEXT=PRIM_MATERIAL_PLASTIC
PRIM_MATERIAL_PLASTIC
!
!TEXT=PRIM_MATERIAL_RUBBER
PRIM_MATERIAL_RUBBER
!
!TEXT=PRIM_MATERIAL_STONE
PRIM_MATERIAL_STONE
!
!TEXT=PRIM_MATERIAL_WOOD
PRIM_MATERIAL_WOOD
!
!TEXT=PRIM_PHANTOM
PRIM_PHANTOM
!
!TEXT=PRIM_PHYSICS
PRIM_PHYSICS
!
!TEXT=PRIM_POSITION
PRIM_POSITION
!
!TEXT=PRIM_ROTATION
PRIM_ROTATION
!
!TEXT=PRIM_SHINY_HIGH
PRIM_SHINY_HIGH
!
!TEXT=PRIM_SHINY_LOW
PRIM_SHINY_LOW
!
!TEXT=PRIM_SHINY_MEDIUM
PRIM_SHINY_MEDIUM
!
!TEXT=PRIM_SHINY_NONE
PRIM_SHINY_NONE
!
!TEXT=PRIM_SIZE
PRIM_SIZE
!
!TEXT=PRIM_TEMP_ON_REZ
PRIM_TEMP_ON_REZ
!
!TEXT=PRIM_TEXTURE
PRIM_TEXTURE
!
!TEXT=PRIM_TYPE
PRIM_TYPE
!
!TEXT=PRIM_TYPE_BOX
PRIM_TYPE_BOX
!
!TEXT=PRIM_TYPE_CYLINDER
PRIM_TYPE_CYLINDER
!
!TEXT=PRIM_TYPE_PRISM
PRIM_TYPE_PRISM
!
!TEXT=PRIM_TYPE_RING
PRIM_TYPE_RING
!
!TEXT=PRIM_TYPE_SPHERE
PRIM_TYPE_SPHERE
!
!TEXT=PRIM_TYPE_TORUS
PRIM_TYPE_TORUS
!
!TEXT=PRIM_TYPE_TUBE
PRIM_TYPE_TUBE
!
!TEXT=PSYS_PART_BOUNCE_MASK
PSYS_PART_BOUNCE_MASK
!
!TEXT=PSYS_PART_EMISSIVE_MASK
PSYS_PART_EMISSIVE_MASK
!
!TEXT=PSYS_PART_END_ALPHA
PSYS_PART_END_ALPHA
!
!TEXT=PSYS_PART_END_COLOR
PSYS_PART_END_COLOR
!
!TEXT=PSYS_PART_END_SCALE
PSYS_PART_END_SCALE
!
!TEXT=PSYS_PART_FLAGS
PSYS_PART_FLAGS
!
!TEXT=PSYS_PART_FOLLOW_SRC_MASK
PSYS_PART_FOLLOW_SRC_MASK
!
!TEXT=PSYS_PART_FOLLOW_VELOCITY_MASK
PSYS_PART_FOLLOW_VELOCITY_MASK
!
!TEXT=PSYS_PART_INTERP_COLOR_MASK
PSYS_PART_INTERP_COLOR_MASK
!
!TEXT=PSYS_PART_INTERP_SCALE_MASK
PSYS_PART_INTERP_SCALE_MASK
!
!TEXT=PSYS_PART_MAX_AGE
PSYS_PART_MAX_AGE
!
!TEXT=PSYS_PART_START_ALPHA
PSYS_PART_START_ALPHA
!
!TEXT=PSYS_PART_START_COLOR
PSYS_PART_START_COLOR
!
!TEXT=PSYS_PART_START_SCALE
PSYS_PART_START_SCALE
!
!TEXT=PSYS_PART_TARGET_LINEAR_MASK
PSYS_PART_TARGET_LINEAR_MASK
!
!TEXT=PSYS_PART_TARGET_POS_MASK
PSYS_PART_TARGET_POS_MASK
!
!TEXT=PSYS_PART_WIND_MASK
PSYS_PART_WIND_MASK
!
!TEXT=PSYS_SRC_ACCEL
PSYS_SRC_ACCEL
!
!TEXT=PSYS_SRC_ANGLE_BEGIN
PSYS_SRC_ANGLE_BEGIN
!
!TEXT=PSYS_SRC_ANGLE_END
PSYS_SRC_ANGLE_END
!
!TEXT=PSYS_SRC_BURST_PART_COUNT
PSYS_SRC_BURST_PART_COUNT
!
!TEXT=PSYS_SRC_BURST_RADIUS
PSYS_SRC_BURST_RADIUS
!
!TEXT=PSYS_SRC_BURST_RATE
PSYS_SRC_BURST_RATE
!
!TEXT=PSYS_SRC_BURST_SPEED_MAX
PSYS_SRC_BURST_SPEED_MAX
!
!TEXT=PSYS_SRC_BURST_SPEED_MIN
PSYS_SRC_BURST_SPEED_MIN
!
!TEXT=PSYS_SRC_INNERANGLE
PSYS_SRC_INNERANGLE
!
!TEXT=PSYS_SRC_MAX_AGE
PSYS_SRC_MAX_AGE
!
!TEXT=PSYS_SRC_OBJ_REL_MASK
PSYS_SRC_OBJ_REL_MASK
!
!TEXT=PSYS_SRC_OMEGA
PSYS_SRC_OMEGA
!
!TEXT=PSYS_SRC_OUTERANGLE
PSYS_SRC_OUTERANGLE
!
!TEXT=PSYS_SRC_PATTERN
PSYS_SRC_PATTERN
!
!TEXT=PSYS_SRC_PATTERN_ANGLE
PSYS_SRC_PATTERN_ANGLE
!
!TEXT=PSYS_SRC_PATTERN_ANGLE_CONE
PSYS_SRC_PATTERN_ANGLE_CONE
!
!TEXT=PSYS_SRC_PATTERN_ANGLE_CONE_EMPTY
PSYS_SRC_PATTERN_ANGLE_CONE_EMPTY
!
!TEXT=PSYS_SRC_PATTERN_DROP
PSYS_SRC_PATTERN_DROP
!
!TEXT=PSYS_SRC_PATTERN_EXPLODE
PSYS_SRC_PATTERN_EXPLODE
!
!TEXT=PSYS_SRC_TARGET_KEY
PSYS_SRC_TARGET_KEY
!
!TEXT=PSYS_SRC_TEXTURE
PSYS_SRC_TEXTURE
!
!TEXT=REMOTE_DATA_CHANNEL
REMOTE_DATA_CHANNEL
!
!TEXT=REMOTE_DATA_REPLY
REMOTE_DATA_REPLY
!
!TEXT=REMOTE_DATA_REQUEST
REMOTE_DATA_REQUEST
!
!TEXT=REVERSE
REVERSE
!
!TEXT=ROTATE
ROTATE
!
!TEXT=SCALE
SCALE
!
!TEXT=SCRIPTED
SCRIPTED
!
!TEXT=SMOOTH
SMOOTH
!
!TEXT=STATUS_BLOCK_GRAB
STATUS_BLOCK_GRAB
!
!TEXT=STATUS_DIE_AT_EDGE
STATUS_DIE_AT_EDGE
!
!TEXT=STATUS_PHANTOM
STATUS_PHANTOM
!
!TEXT=STATUS_PHYSICS
STATUS_PHYSICS
!
!TEXT=STATUS_RETURN_AT_EDGE
STATUS_RETURN_AT_EDGE
!
!TEXT=STATUS_ROTATE_X
STATUS_ROTATE_X
!
!TEXT=STATUS_ROTATE_Y
STATUS_ROTATE_Y
!
!TEXT=STATUS_ROTATE_Z
STATUS_ROTATE_Z
!
!TEXT=STATUS_SANDBOX
STATUS_SANDBOX
!
!TEXT=TRUE
TRUE
!
!TEXT=TYPE_FLOAT
TYPE_FLOAT
!
!TEXT=TYPE_INTEGER
TYPE_INTEGER
!
!TEXT=TYPE_INVALID
TYPE_INVALID
!
!TEXT=TYPE_KEY
TYPE_KEY
!
!TEXT=TYPE_ROTATION
TYPE_ROTATION
!
!TEXT=TYPE_STRING
TYPE_STRING
!
!TEXT=TYPE_VECTOR
TYPE_VECTOR
!
!TEXT=VEHICLE_ANGULAR_DEFLECTION_EFFICIENCY
VEHICLE_ANGULAR_DEFLECTION_EFFICIENCY
!
!TEXT=VEHICLE_ANGULAR_DEFLECTION_TIMESCALE
VEHICLE_ANGULAR_DEFLECTION_TIMESCALE
!
!TEXT=VEHICLE_ANGULAR_FRICTION_TIMESCALE
VEHICLE_ANGULAR_FRICTION_TIMESCALE
!
!TEXT=VEHICLE_ANGULAR_MOTOR_DECAY_TIMESCALE
VEHICLE_ANGULAR_MOTOR_DECAY_TIMESCALE
!
!TEXT=VEHICLE_ANGULAR_MOTOR_DIRECTION
VEHICLE_ANGULAR_MOTOR_DIRECTION
!
!TEXT=VEHICLE_ANGULAR_MOTOR_TIMESCALE
VEHICLE_ANGULAR_MOTOR_TIMESCALE
!
!TEXT=VEHICLE_BANKING_EFFICIENCY
VEHICLE_BANKING_EFFICIENCY
!
!TEXT=VEHICLE_BANKING_MIX
VEHICLE_BANKING_MIX
!
!TEXT=VEHICLE_BANKING_TIMESCALE
VEHICLE_BANKING_TIMESCALE
!
!TEXT=VEHICLE_BUOYANCY
VEHICLE_BUOYANCY
!
!TEXT=VEHICLE_FLAG_CAMERA_DECOUPLED
VEHICLE_FLAG_CAMERA_DECOUPLED
!
!TEXT=VEHICLE_FLAG_HOVER_GLOBAL_HEIGHT
VEHICLE_FLAG_HOVER_GLOBAL_HEIGHT
!
!TEXT=VEHICLE_FLAG_HOVER_TERRAIN_ONLY
VEHICLE_FLAG_HOVER_TERRAIN_ONLY
!
!TEXT=VEHICLE_FLAG_HOVER_UP_ONLY
VEHICLE_FLAG_HOVER_UP_ONLY
!
!TEXT=VEHICLE_FLAG_HOVER_WATER_ONLY
VEHICLE_FLAG_HOVER_WATER_ONLY
!
!TEXT=VEHICLE_FLAG_LIMIT_MOTOR_UP
VEHICLE_FLAG_LIMIT_MOTOR_UP
!
!TEXT=VEHICLE_FLAG_LIMIT_ROLL_ONLY
VEHICLE_FLAG_LIMIT_ROLL_ONLY
!
!TEXT=VEHICLE_FLAG_MOUSELOOK_BANK
VEHICLE_FLAG_MOUSELOOK_BANK
!
!TEXT=VEHICLE_FLAG_MOUSELOOK_STEER
VEHICLE_FLAG_MOUSELOOK_STEER
!
!TEXT=VEHICLE_FLAG_NO_DEFLECTION_UP
VEHICLE_FLAG_NO_DEFLECTION_UP
!
!TEXT=VEHICLE_FLAG_NO_FLY_UP
VEHICLE_FLAG_NO_FLY_UP
!
!TEXT=VEHICLE_HOVER_EFFICIENCY
VEHICLE_HOVER_EFFICIENCY
!
!TEXT=VEHICLE_HOVER_HEIGHT
VEHICLE_HOVER_HEIGHT
!
!TEXT=VEHICLE_HOVER_TIMESCALE
VEHICLE_HOVER_TIMESCALE
!
!TEXT=VEHICLE_LINEAR_DEFLECTION_EFFICIENCY
VEHICLE_LINEAR_DEFLECTION_EFFICIENCY
!
!TEXT=VEHICLE_LINEAR_DEFLECTION_TIMESCALE
VEHICLE_LINEAR_DEFLECTION_TIMESCALE
!
!TEXT=VEHICLE_LINEAR_FRICTION_TIMESCALE
VEHICLE_LINEAR_FRICTION_TIMESCALE
!
!TEXT=VEHICLE_LINEAR_MOTOR_DECAY_TIMESCALE
VEHICLE_LINEAR_MOTOR_DECAY_TIMESCALE
!
!TEXT=VEHICLE_LINEAR_MOTOR_DIRECTION
VEHICLE_LINEAR_MOTOR_DIRECTION
!
!TEXT=VEHICLE_LINEAR_MOTOR_OFFSET
VEHICLE_LINEAR_MOTOR_OFFSET
!
!TEXT=VEHICLE_LINEAR_MOTOR_TIMESCALE
VEHICLE_LINEAR_MOTOR_TIMESCALE
!
!TEXT=VEHICLE_REFERENCE_FRAME
VEHICLE_REFERENCE_FRAME
!
!TEXT=VEHICLE_TYPE_AIRPLANE
VEHICLE_TYPE_AIRPLANE
!
!TEXT=VEHICLE_TYPE_BALLOON
VEHICLE_TYPE_BALLOON
!
!TEXT=VEHICLE_TYPE_BOAT
VEHICLE_TYPE_BOAT
!
!TEXT=VEHICLE_TYPE_CAR
VEHICLE_TYPE_CAR
!
!TEXT=VEHICLE_TYPE_NONE
VEHICLE_TYPE_NONE
!
!TEXT=VEHICLE_TYPE_SLED
VEHICLE_TYPE_SLED
!
!TEXT=VEHICLE_VERTICAL_ATTRACTION_EFFICIENCY
VEHICLE_VERTICAL_ATTRACTION_EFFICIENCY
!
!TEXT=VEHICLE_VERTICAL_ATTRACTION_TIMESCALE
VEHICLE_VERTICAL_ATTRACTION_TIMESCALE
!
!TEXT=PI 	
PI 	
!
!TEXT=TWO_PI 	
TWO_PI 	
!
!TEXT=PI_BY_TWO 	
PI_BY_TWO 	
!
!TEXT=DEG_TO_RAD 	
DEG_TO_RAD 	
!
!TEXT=RAD_TO_DEG 	
RAD_TO_DEG 	
!
!TEXT=SQRT2 	
SQRT2 	
!
!TEXT=NULL_KEY
NULL_KEY
!
!TEXT=EOF
EOF
!
!TEXT=ZERO_ROTATION
ZERO_ROTATION
!
!TEXT=ZERO_VECTOR
ZERO_VECTOR
!
!TEXT=llAbs
llAbs(\^)
!
!TEXT=llAcos
llAcos(\^)
!
!TEXT=llAddToLandPassList
llAddToLandPassList(\^)
!
!TEXT=llAdjustSoundVolume
llAdjustSoundVolume(\^)
!
!TEXT=llAllowInventoryDrop
llAllowInventoryDrop(\^)
!
!TEXT=llAngleBetween
llAngleBetween(\^)
!
!TEXT=llApplyImpulse
llApplyImpulse(\^)
!
!TEXT=llApplyRotationalImpulse
llApplyRotationalImpulse(\^)
!
!TEXT=llAsin
llAsin(\^)
!
!TEXT=llAtan2
llAtan2(\^)
!
!TEXT=llAttachToAvatar
llAttachToAvatar(\^)
!
!TEXT=llAvatarOnSitTarget
llAvatarOnSitTarget(\^)
!
!TEXT=llAxisAngle2Rot
llAxisAngle2Rot(\^)
!
!TEXT=llBase64ToString
llBase64ToString(\^)
!
!TEXT=llBreakAllLinks
llBreakAllLinks(\^)
!
!TEXT=llBreakLink
llBreakLink(\^)
!
!TEXT=llCSV2List
llCSV2List(\^)
!
!TEXT=llCeil
llCeil(\^)
!
!TEXT=llCloseRemoteDataChannel
llCloseRemoteDataChannel(\^)
!
!TEXT=llCloud
llCloud(\^)
!
!TEXT=llCollisionFilter
llCollisionFilter(\^)
!
!TEXT=llCollisionSound
llCollisionSound(\^)
!
!TEXT=llCollisionSprite
llCollisionSprite(\^)
!
!TEXT=llCos
llCos(\^)
!
!TEXT=llCreateLink
llCreateLink(\^)
!
!TEXT=llDeleteSubList
llDeleteSubList(\^)
!
!TEXT=llDeleteSubString
llDeleteSubString(\^)
!
!TEXT=llDetachFromAvatar
llDetachFromAvatar(\^)
!
!TEXT=llDetectedGrab
llDetectedGrab(\^)
!
!TEXT=llDetectedGroup
llDetectedGroup(\^)
!
!TEXT=llDetectedKey
llDetectedKey(\^)
!
!TEXT=llDetectedLinkNumber
llDetectedLinkNumber(\^)
!
!TEXT=llDetectedName
llDetectedName(\^)
!
!TEXT=llDetectedOwner
llDetectedOwner(\^)
!
!TEXT=llDetectedPos
llDetectedPos(\^)
!
!TEXT=llDetectedRot
llDetectedRot(\^)
!
!TEXT=llDetectedType
llDetectedType(\^)
!
!TEXT=llDetectedVel
llDetectedVel(\^)
!
!TEXT=llDialog
llDialog(\^)
!
!TEXT=llDie
llDie(\^)
!
!TEXT=llDumpList2String
llDumpList2String(\^)
!
!TEXT=llEdgeOfWorld
llEdgeOfWorld(\^)
!
!TEXT=llEjectFromLand
llEjectFromLand(\^)
!
!TEXT=llEmail
llEmail(\^)
!
!TEXT=llEuler2Rot
llEuler2Rot(\^)
!
!TEXT=llFabs
llFabs(\^)
!
!TEXT=llFloor
llFloor(\^)
!
!TEXT=llFrand
llFrand(\^)
!
!TEXT=llFrand51
llFrand51(\^)
!
!TEXT=llGetAccel
llGetAccel(\^)
!
!TEXT=llGetAgentInfo
llGetAgentInfo(\^)
!
!TEXT=llGetAgentSize
llGetAgentSize(\^)
!
!TEXT=llGetAlpha
llGetAlpha(\^)
!
!TEXT=llGetAndResetTime
llGetAndResetTime(\^)
!
!TEXT=llGetAnimation
llGetAnimation(\^)
!
!TEXT=llGetAnimationList
llGetAnimationList(\^)
!
!TEXT=llGetAttached
llGetAttached(\^)
!
!TEXT=llGetCenterOfMass
llGetCenterOfMass(\^)
!
!TEXT=llGetColor
llGetColor(\^)
!
!TEXT=llGetDate
llGetDate(\^)
!
!TEXT=llGetEnergy
llGetEnergy(\^)
!
!TEXT=llGetForce
llGetForce(\^)
!
!TEXT=llGetFreeMemory
llGetFreeMemory(\^)
!
!TEXT=llGetInventoryKey
llGetInventoryKey(\^)
!
!TEXT=llGetInventoryName
llGetInventoryName(\^)
!
!TEXT=llGetInventoryNumber
llGetInventoryNumber(\^)
!
!TEXT=llGetKey
llGetKey(\^)
!
!TEXT=llGetLandOwnerAt
llGetLandOwnerAt(\^)
!
!TEXT=llGetLinkKey
llGetLinkKey(\^)
!
!TEXT=llGetLinkName
llGetLinkName(\^)
!
!TEXT=llGetLinkNumber
llGetLinkNumber(\^)
!
!TEXT=llGetListEntryType
llGetListEntryType(\^)
!
!TEXT=llGetListLength
llGetListLength(\^)
!
!TEXT=llGetLocalPos
llGetLocalPos(\^)
!
!TEXT=llGetLocalRot
llGetLocalRot(\^)
!
!TEXT=llGetMass
llGetMass(\^)
!
!TEXT=llGetNextEmail
llGetNextEmail(\^)
!
!TEXT=llGetNotecardLine
llGetNotecardLine(\^)
!
!TEXT=llGetNumberOfNotecardLines
llGetNumberOfNotecardLines(\^)
!
!TEXT=llGetNumberOfPrims
llGetNumberOfPrims(\^)
!
!TEXT=llGetNumberOfSides
llGetNumberOfSides(\^)
!
!TEXT=llGetObjectName
llGetObjectName(\^)
!
!TEXT=llGetOmega
llGetOmega(\^)
!
!TEXT=llGetOwner
llGetOwner(\^)
!
!TEXT=llGetOwnerKey
llGetOwnerKey(\^)
!
!TEXT=llGetPermissions
llGetPermissions(\^)
!
!TEXT=llGetPermissionsKey
llGetPermissionsKey(\^)
!
!TEXT=llGetPos
llGetPos(\^)
!
!TEXT=llGetRegionCorner
llGetRegionCorner(\^)
!
!TEXT=llGetRegionFPS
llGetRegionFPS(\^)
!
!TEXT=llGetRegionName
llGetRegionName(\^)
!
!TEXT=llGetRegionTimeDilation
llGetRegionTimeDilation(\^)
!
!TEXT=llGetRot
llGetRot(\^)
!
!TEXT=llGetScale
llGetScale(\^)
!
!TEXT=llGetScriptName
llGetScriptName(\^)
!
!TEXT=llGetScriptState
llGetScriptState(\^)
!
!TEXT=llGetStartParameter
llGetStartParameter(\^)
!
!TEXT=llGetStatus
llGetStatus(\^)
!
!TEXT=llGetSubString
llGetSubString(\^)
!
!TEXT=llGetSunDirection
llGetSunDirection(\^)
!
!TEXT=llGetTexture
llGetTexture(\^)
!
!TEXT=llGetTextureOffset
llGetTextureOffset(\^)
!
!TEXT=llGetTextureRot
llGetTextureRot(\^)
!
!TEXT=llGetTextureScale
llGetTextureScale(\^)
!
!TEXT=llGetTime
llGetTime(\^)
!
!TEXT=llGetTimeOfDay
llGetTimeOfDay(\^)
!
!TEXT=llGetTorque
llGetTorque(\^)
!
!TEXT=llGetVel
llGetVel(\^)
!
!TEXT=llGetWallclock
llGetWallclock(\^)
!
!TEXT=llGiveInventory
llGiveInventory(\^)
!
!TEXT=llGiveInventoryList
llGiveInventoryList(\^)
!
!TEXT=llGiveMoney
llGiveMoney(\^)
!
!TEXT=llGodLikeRezObject
llGodLikeRezObject(\^)
!
!TEXT=llGround
llGround(\^)
!
!TEXT=llGroundContour
llGroundContour(\^)
!
!TEXT=llGroundNormal
llGroundNormal(\^)
!
!TEXT=llGroundRepel
llGroundRepel(\^)
!
!TEXT=llGroundSlope
llGroundSlope(\^)
!
!TEXT=llInsertString
llInsertString(\^)
!
!TEXT=llInstantMessage
llInstantMessage(\^)
!
!TEXT=llKey2Name
llKey2Name(\^)
!
!TEXT=llList2CSV
llList2CSV(\^)
!
!TEXT=llList2Float
llList2Float(\^)
!
!TEXT=llList2Integer
llList2Integer(\^)
!
!TEXT=llList2Key
llList2Key(\^)
!
!TEXT=llList2List
llList2List(\^)
!
!TEXT=llList2ListStrided
llList2ListStrided(\^)
!
!TEXT=llList2Rot
llList2Rot(\^)
!
!TEXT=llList2String
llList2String(\^)
!
!TEXT=llList2Vector
llList2Vector(\^)
!
!TEXT=llListFindList
llListFindList(\^)
!
!TEXT=llListInsertList
llListInsertList(\^)
!
!TEXT=llListRandomize
llListRandomize(\^)
!
!TEXT=llListSort
llListSort(\^)
!
!TEXT=llListen
llListen(\^)
!
!TEXT=llListenControl
llListenControl(\^)
!
!TEXT=llListenRemove
llListenRemove(\^)
!
!TEXT=llLog
llLog(\^)
!
!TEXT=llLog10
llLog10(\^)
!
!TEXT=llLookAt
llLookAt(\^)
!
!TEXT=llLoopSound
llLoopSound(\^)
!
!TEXT=llLoopSoundMaster
llLoopSoundMaster(\^)
!
!TEXT=llLoopSoundSlave
llLoopSoundSlave(\^)
!
!TEXT=llMD5String
llMD5String(\^)
!
!TEXT=llMakeExplosion
llMakeExplosion(\^)
!
!TEXT=llMakeFire
llMakeFire(\^)
!
!TEXT=llMakeFountain
llMakeFountain(\^)
!
!TEXT=llMakeSmoke
llMakeSmoke(\^)
!
!TEXT=llMessageLinked
llMessageLinked(\^)
!
!TEXT=llMinEventDelay
llMinEventDelay(\^)
!
!TEXT=llModifyLand
llModifyLand(\^)
!
!TEXT=llMoveToTarget
llMoveToTarget(\^)
!
!TEXT=llOffsetTexture
llOffsetTexture(\^)
!
!TEXT=llOpenRemoteDataChannel
llOpenRemoteDataChannel(\^)
!
!TEXT=llOverMyLand
llOverMyLand(\^)
!
!TEXT=llOwnerSay
llOwnerSay(\^)
!
!TEXT=llParseString2List
llParseString2List(\^)
!
!TEXT=llParticleSystem
llParticleSystem(\^)
!
!TEXT=llPassCollisions
llPassCollisions(\^)
!
!TEXT=llPassTouches
llPassTouches(\^)
!
!TEXT=llPlaySound
llPlaySound(\^)
!
!TEXT=llPlaySoundSlave
llPlaySoundSlave(\^)
!
!TEXT=llPointAt
llPointAt(\^)
!
!TEXT=llPow
llPow(\^)
!
!TEXT=llPreloadSound
llPreloadSound(\^)
!
!TEXT=llPushObject
llPushObject(\^)
!
!TEXT=llReleaseCamera
llReleaseCamera(\^)
!
!TEXT=llReleaseControls
llReleaseControls(\^)
!
!TEXT=llRemoteDataReply
llRemoteDataReply(\^)
!
!TEXT=llRemoteDataSetRegion
llRemoteDataSetRegion(\^)
!
!TEXT=llRemoteLoadScript
llRemoteLoadScript(\^)
!
!TEXT=llRemoteLoadScriptPin
llRemoteLoadScriptPin(\^)
!
!TEXT=llRemoveInventory
llRemoveInventory(\^)
!
!TEXT=llRemoveVehicleFlags
llRemoveVehicleFlags(\^)
!
!TEXT=llRequestAgentData
llRequestAgentData(\^)
!
!TEXT=llRequestInventoryData
llRequestInventoryData(\^)
!
!TEXT=llRequestPermissions
llRequestPermissions(\^)
!
!TEXT=llResetOtherScript
llResetOtherScript(\^)
!
!TEXT=llResetScript
llResetScript(\^)
!
!TEXT=llResetTime
llResetTime(\^)
!
!TEXT=llRezObject
llRezObject(\^)
!
!TEXT=llRot2Angle
llRot2Angle(\^)
!
!TEXT=llRot2Axis
llRot2Axis(\^)
!
!TEXT=llRot2Euler
llRot2Euler(\^)
!
!TEXT=llRot2Fwd
llRot2Fwd(\^)
!
!TEXT=llRot2Left
llRot2Left(\^)
!
!TEXT=llRot2Up
llRot2Up(\^)
!
!TEXT=llRotBetween
llRotBetween(\^)
!
!TEXT=llRotLookAt
llRotLookAt(\^)
!
!TEXT=llRotTarget
llRotTarget(\^)
!
!TEXT=llRotTargetRemove
llRotTargetRemove(\^)
!
!TEXT=llRotateTexture
llRotateTexture(\^)
!
!TEXT=llRound
llRound(\^)
!
!TEXT=llSameGroup
llSameGroup(\^)
!
!TEXT=llSay
llSay(\^)
!
!TEXT=llScaleTexture
llScaleTexture(\^)
!
!TEXT=llScriptDanger
llScriptDanger(\^)
!
!TEXT=llSendRemoteData
llSendRemoteData(\^)
!
!TEXT=llSensor
llSensor(\^)
!
!TEXT=llSensorRemove
llSensorRemove(\^)
!
!TEXT=llSensorRepeat
llSensorRepeat(\^)
!
!TEXT=llSetAlpha
llSetAlpha(\^)
!
!TEXT=llSetBuoyancy
llSetBuoyancy(\^)
!
!TEXT=llSetCameraAtOffset
llSetCameraAtOffset(\^)
!
!TEXT=llSetCameraEyeOffset
llSetCameraEyeOffset(\^)
!
!TEXT=llSetColor
llSetColor(\^)
!
!TEXT=llSetDamage
llSetDamage(\^)
!
!TEXT=llSetForce
llSetForce(\^)
!
!TEXT=llSetForceAndTorque
llSetForceAndTorque(\^)
!
!TEXT=llSetHoverHeight
llSetHoverHeight(\^)
!
!TEXT=llSetLinkColor
llSetLinkColor(\^)
!
!TEXT=llSetObjectDesc
llSetObjectDesc(\^)
!
!TEXT=llSetObjectName
llSetObjectName(\^)
!
!TEXT=llSetParcelMusicURL
llSetParcelMusicURL(\^)
!
!TEXT=llSetPos
llSetPos(\^)
!
!TEXT=llSetPrimitiveParams
llSetPrimitiveParams(\^)
!
!TEXT=llSetRemoteScriptAccessPin
llSetRemoteScriptAccessPin(\^)
!
!TEXT=llSetRot
llSetRot(\^)
!
!TEXT=llSetScale
llSetScale(\^)
!
!TEXT=llSetScriptState
llSetScriptState(\^)
!
!TEXT=llSetSitText
llSetSitText(\^)
!
!TEXT=llSetSoundQueueing
llSetSoundQueueing(\^)
!
!TEXT=llSetSoundRadius
llSetSoundRadius(\^)
!
!TEXT=llSetStatus
llSetStatus(\^)
!
!TEXT=llSetText
llSetText(\^)
!
!TEXT=llSetTexture
llSetTexture(\^)
!
!TEXT=llSetTextureAnim
llSetTextureAnim(\^)
!
!TEXT=llSetTimerEvent
llSetTimerEvent(\^)
!
!TEXT=llSetTorque
llSetTorque(\^)
!
!TEXT=llSetTouchText
llSetTouchText(\^)
!
!TEXT=llSetVehicleFlags
llSetVehicleFlags(\^)
!
!TEXT=llSetVehicleFloatParam
llSetVehicleFloatParam(\^)
!
!TEXT=llSetVehicleRotationParam
llSetVehicleRotationParam(\^)
!
!TEXT=llSetVehicleType
llSetVehicleType(\^)
!
!TEXT=llSetVehicleVectorParam
llSetVehicleVectorParam(\^)
!
!TEXT=llShout
llShout(\^)
!
!TEXT=llSin
llSin(\^)
!
!TEXT=llSitTarget
llSitTarget(\^)
!
!TEXT=llSleep
llSleep(\^)
!
!TEXT=llSound
llSound(\^)
!
!TEXT=llSoundPreload
llSoundPreload(\^)
!
!TEXT=llSqrt
llSqrt(\^)
!
!TEXT=llStartAnimation
llStartAnimation(\^)
!
!TEXT=llStopAnimation
llStopAnimation(\^)
!
!TEXT=llStopHover
llStopHover(\^)
!
!TEXT=llStopLookAt
llStopLookAt(\^)
!
!TEXT=llStopMoveToTarget
llStopMoveToTarget(\^)
!
!TEXT=llStopPointAt
llStopPointAt(\^)
!
!TEXT=llStopSound
llStopSound(\^)
!
!TEXT=llStringLength
llStringLength(\^)
!
!TEXT=llStringToBase64
llStringToBase64(\^)
!
!TEXT=llSubStringIndex
llSubStringIndex(\^)
!
!TEXT=llTakeCamera
llTakeCamera(\^)
!
!TEXT=llTakeControls
llTakeControls(\^)
!
!TEXT=llTan
llTan(\^)
!
!TEXT=llTarget
llTarget(\^)
!
!TEXT=llTargetOmega
llTargetOmega(\^)
!
!TEXT=llTargetRemove
llTargetRemove(\^)
!
!TEXT=llTeleportAgentHome
llTeleportAgentHome(\^)
!
!TEXT=llToLower
llToLower(\^)
!
!TEXT=llToUpper
llToUpper(\^)
!
!TEXT=llTriggerSound
llTriggerSound(\^)
!
!TEXT=llTriggerSoundLimited
llTriggerSoundLimited(\^)
!
!TEXT=llUnSit
llUnSit(\^)
!
!TEXT=llVecDist
llVecDist(\^)
!
!TEXT=llVecMag
llVecMag(\^)
!
!TEXT=llVecNorm
llVecNorm(\^)
!
!TEXT=llVolumeDetect
llVolumeDetect(\^)
!
!TEXT=llWater
llWater(\^)
!
!TEXT=llWhisper
llWhisper(\^)
!
!TEXT=llWind
llWind(\^)
!
!TEXT=llXorBase64Strings
llXorBase64Strings(\^)
!
